server:
  error:
    whitelabel:
      enabled: true
discord:
  apiUrl: https://discord.com/api/
  cdnUrl: https://cdn.discordapp.com/
spring:
  application:
    name: discord-dkp-bot
#  profiles:
#    active: ${PROFILE}
  datasource:
    url: jdbc:postgresql://localhost:5432/discord-bot-dev
    username: bot
    password: bottest
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: embedded
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  security:
    oauth2:
      client:
        registration:
          discord:
            redirect-uri: "{baseUrl}/login/oauth2/code/discord"
            authorization-grant-type: authorization_code
            client-id: 752438109395877969
            client-name: A1nu-dev
            client-secret: GPXJdA_VsThrpfBqMidF8LsjHGqtmINZ
            client-authentication-method: client_secret_post
            scope: [ identify, email, guilds ]
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discordapp.com/api/users/@me
            user-name-attribute: username
